

describe('empty spec', () => {
  it('passes', () => {
    // cy.visit('https://example.cypress.io')
    cy.visit('http://localhost:3000/time_set')
    cy.get('input[name="time"]').type('2017-06-01T08:30:01')
    cy.contains(' Set Time ').click()
    cy.contains('Clear Data').click()
    cy.visit('http://localhost:3000/time_set')
    cy.get('input[name="time"]').type('2017-06-01T08:30:01')
    cy.contains(' Set Time ').click()

    cy.contains('User Login').click()
    cy.contains('Sign Up').click()
    cy.get('[placeholder="Email"]').type('12345698@163.com')
    cy.get('[placeholder="Password"]').type('123poi,')
    cy.get('[placeholder="First Name"]').type('Sam')
    cy.get('[placeholder="Last Name"]').type('Smith')
    cy.get('[placeholder="Address"]').type('1 Lorn St')
    cy.contains('WeChat').click()
    cy.get('[placeholder="Account 3-40 characters"]').type('661133')
    cy.get('.userSign').click()
    cy.contains('Logout').click()

    cy.visit('http://localhost:3000/')
    cy.contains('Clear Token').click()


    cy.contains('User Login').click()
    cy.get('[placeholder="Email"]').type('12345698@163.com')
    cy.get('[placeholder="Password"]').type('123poi,')

    cy.get('.userLogin').click()
    cy.contains('Add Balance').click()
    cy.get('button').filter(':contains("+ 50")').click()
    cy.get('button').filter(':contains("Submit")').click()
    cy.wait(100)
    cy.contains('Maybe You Like').click()
    cy.wait(100)
    cy.contains(" Guess you like ").click()
    cy.contains(" Describe similar ").click()
    cy.contains("My Detail").click()
    cy.contains("Back to home page").click()
    cy.get('[name="notification-btn"]').click()
    cy.get('[name = "closeNoti"]').click()
    cy.contains('Logout').click()
    cy.contains(' All Information ').click()
    cy.contains('Back to home page').click()
    
    cy.contains(' Push Now Time ').click()
    cy.get('[placeholder="week"]').type('1')
    cy.get('[placeholder="day"]').type('1')
    cy.get('[placeholder="hour"]').type('1')
    cy.get('[placeholder="minute"]').type('1')
    cy.get('[placeholder="second"]').type('1')
    cy.contains(' Set Time ').click()
    // cy.get('placeholder="Email"')
  })
})